config/routes.rb
Invoicer::Application.routes.draw do
  resources :invoicefields

  resources :invoices

  resources :customers

  get "welcome/index"

  get "welcome/credits"

  root :to => 'welcome#index'

end

app/models/invoicefield.rb
class Invoicefield < ActiveRecord::Base
  belongs_to :invoice
  attr_accessible :amount, :invoice_id, :title, :fieldtype, :units, :rate
  
  validates_numericality_of :amount
  
  FIELD_TYPES = ["fixed_amount", "percentage", "fixed_tax", "percentage_tax"]
  
  def translated_field_type
    I18n.t(field_type, :scope => :field_types)
  end
end

app/controllers/invoicefields_controller.rb
class InvoicefieldsController < ApplicationController
  # GET /invoicefields
  # GET /invoicefields.json
  def index
    @invoicefields = Invoicefield.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoicefields }
    end
  end

  # GET /invoicefields/1
  # GET /invoicefields/1.json
  def show
    @invoicefield = Invoicefield.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoicefield }
    end
  end

  # GET /invoicefields/new
  # GET /invoicefields/new.json
  def new
    @invoicefield = Invoicefield.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoicefield }
    end
  end

  # GET /invoicefields/1/edit
  def edit
    @invoicefield = Invoicefield.find(params[:id])
  end

  # POST /invoicefields
  # POST /invoicefields.json
  def create
    @invoicefield = Invoicefield.new(params[:invoicefield])
    
    respond_to do |format|
      if @invoicefield.save
        format.html { redirect_to @invoicefield, notice: 'Invoicefield was successfully created.' }
        format.json { render json: @invoicefield, status: :created, location: @invoicefield }
      else
        format.html { render action: "new" }
        format.json { render json: @invoicefield.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoicefields/1
  # PUT /invoicefields/1.json
  def update
    @invoicefield = Invoicefield.find(params[:id])

    respond_to do |format|
      if @invoicefield.update_attributes(params[:invoicefield])
        format.html { redirect_to @invoicefield, notice: 'Invoicefield was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoicefield.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoicefields/1
  # DELETE /invoicefields/1.json
  def destroy
    @invoicefield = Invoicefield.find(params[:id])
    @invoicefield.destroy

    respond_to do |format|
      format.html { redirect_to invoicefields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invoicefields_helper.rb
module InvoicefieldsHelper
  def field_types
    I18n.t(:field_types).map { |key, value| [ value, key ] }
  end
end

app/views/invoicefields/_form.html.erb
<%= form_for(@invoicefield) do |f| %>
  <% if @invoicefield.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoicefield.errors.count, "error") %> prohibited this invoicefield from being saved:</h2>

      <ul>
      <% @invoicefield.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :invoice_id %><br />
    <%= f.number_field :invoice_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoicefields/edit.html.erb
<h1>Editing invoicefield</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoicefield %> |
<%= link_to 'Back', invoicefields_path %>

app/views/invoicefields/index.html.erb
<h1>Listing invoicefields</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Title</th>
    <th>Amount</th>
    <th>Invoice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoicefields.each do |invoicefield| %>
  <tr>
    <td><%= invoicefield.type %></td>
    <td><%= invoicefield.title %></td>
    <td><%= invoicefield.amount %></td>
    <td><%= invoicefield.invoice_id %></td>
    <td><%= link_to 'Show', invoicefield %></td>
    <td><%= link_to 'Edit', edit_invoicefield_path(invoicefield) %></td>
    <td><%= link_to 'Destroy', invoicefield, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoicefield', new_invoicefield_path %>

app/views/invoicefields/new.html.erb
<h1>New invoicefield</h1>

<%= render 'form' %>

<%= link_to 'Back', invoicefields_path %>

app/views/invoicefields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @invoicefield.type %>
</p>

<p>
  <b>Title:</b>
  <%= @invoicefield.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @invoicefield.amount %>
</p>

<p>
  <b>Invoice:</b>
  <%= @invoicefield.invoice_id %>
</p>


<%= link_to 'Edit', edit_invoicefield_path(@invoicefield) %> |
<%= link_to 'Back', invoicefields_path %>