config/routes.rb
Invoicer::Application.routes.draw do
  resources :invoicefields

  resources :invoices

  resources :customers

  get "welcome/index"

  get "welcome/credits"

  root :to => 'welcome#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :amount, :customer_id, :expiredate, :status, :invoicetype, :invoicenumber, :invoicefields_attributes
  
  belongs_to :customer
  
  has_many :invoicefields, :dependent => :destroy
  accepts_nested_attributes_for :invoicefields, allow_destroy: true
  
  validates_presence_of :customer_id, :invoicetype
  validates_numericality_of :amount, :allow_blank => true
  validates_numericality_of :invoicenumber, :if => :is_invoice?
  validates_uniqueness_of :invoicenumber, :if => :is_invoice?
  
  validates_presence_of :invoicenumber, :if => :is_invoice?
  
  before_validation :was_quote
  
  before_save :calculate_amount
  
  INVOICE_TYPES = ["Invoice", "Quote"]
  INVOICE_STATUS = ["New", "Paid", "Unpaid"]
  
  def translated_invoice_type
    I18n.t(invoice_type, :scope => :invoice_types)
  end
  
  def translated_invoice_statu
    I18n.t(invoice_statu, :scope => :invoice_status)
  end
  
  def is_invoice?
    invoicetype == "Invoice"
  end
  
  def was_quote
    if invoicetype_was == "Quote" && invoicetype == "Invoice" && invoicenumber == nil
      self.invoicenumber = Invoice.where(:invoicetype => "Invoice").last.invoicenumber += 1
    end
  end
  
  def calculate_amount
    temp = 0.0
    self.invoicefields.each do |field|
      if field.fieldtype == "fixed_amount" || field.fieldtype == "fixed_tax" 
        temp += field.amount      
      else 
        temp += 0
      end
    end
    
    self.invoicefields.each do |field|
      if field.fieldtype == "percentage" || field.fieldtype == "percentage_tax" 
        temp = temp * ( (field.amount / 100.0) + 1 )
      else
        temp += 0
      end
    end
    self.amount = temp.round(2)
  end
  
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.where(:invoicetype => "Invoice")
    @quotes = Invoice.where(:invoicetype => "Quote")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
      #format.js
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(params[:invoice])
    
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def invoice_types
    I18n.t(:invoice_types).map { |key, value| [ value, key ] }
  end
  
  def invoice_status
    I18n.t(:invoice_status).map { |key, value| [ value, key ] }
  end
end

app/views/invoices/_form.html.erb
<% if params[:action] == 'index' %>
	<% remoteform = true %> 
<% else %>
	<% remoteform = false %>
<% end %>

<%= form_for(@invoice, html:{class:"form-horizontal no-margin"}, remote: remoteform)  do |f| %>

 <% if @invoice.errors.any? %>
    <div class="alert alert-error fade in">
    	<button data-dismiss="alert" class="close">×</button>
      <strong><%= pluralize(@invoice.errors.count, "error") %> prohibited this customer from being saved:</strong>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<form class="form-horizontal no-margin">
		<fieldset>
			<div class="control-group">
		  	<%= f.label :invoicenumber, :class => "control-label" %>
			<div class="controls">
				<div class="input-append no-margin">
					<%= f.text_field :invoicenumber %>
				</div>
				<span class="help-inline">
					<% if Invoice.count > 0 %>
						<%= t("Last invoice number is") %> <%= Invoice.where(:invoicetype => "Invoice").last.invoicenumber %></span>
					<% end %>
			</div>
		  </div>
		  
		   <div class="control-group">
		  	<%= f.label :invoicetype, :class => "control-label" %>
			<div class="controls">
				<div class="input-append no-margin">
					<%= f.select :invoicetype, invoice_types, :selected => params[:invoicetype] %>
				</div>
			</div>
		  </div>
		
		  <div class="control-group">
		  	<%= f.label :status, :class => "control-label" %>
			<div class="controls">
				<div class="input-append no-margin">
					<%= f.select :status, invoice_status %>
				</div>
			</div>
		  </div>
		    
		  <div class="control-group">
		  	<%= f.label :expiredate, :class => "control-label" %>
			<div class="controls">
				<div class="input-append no-margin">
					<%= f.text_field :expiredate, :class => "input-small", :value => 4.weeks.from_now.strftime("%d/%m/%Y") %><span class="add-on"><i class="icon-calendar"></i></span>
				</div>
			</div>
		  </div>
		    
		
		  <div class="control-group">
		  	<%= f.label :customer_id, :class => "control-label" %>
			<div class="controls">
				<div class="input-append no-margin">
					<%= f.select(:customer_id, Customer.all.collect {|a| [a.fullname, a.id]}, :include_blank => true ) -%>
				</div>
			</div>
		  </div>
		  
		  <div class="control-group">
		  	<%= f.label :amount, :class => "control-label" %>
			<div class="controls">
				<div class="no-margin uneditable-input">
					<%= @invoice.amount if !@invoice.amount.nil? %>
				</div>
			</div>
		  </div> 
		
		  <div class="control-group">
			  <%= f.fields_for :invoicefields do |builder| %>
			  	<%= render 'invoicefield_fields', f: builder %>
			  <% end %>
			  <%= link_to_add_fields t("Add field"), f, :invoicefields %>
		  </div>
			
			<div class="form-actions">
				<%= f.submit t('Save changes'), :class => "btn btn-alt btn-large btn-primary" %>
			</div>
		</fieldset>
	</form>
<% end %>



<%= javascript_include_tag "bootstrap-datepicker" %>

<script src="/js/invoice_form.js"></script>

app/views/invoices/_invoice.html.erb
											<td><%= invoice.invoicenumber %></td>
										    <td>									    											    	
										    	<% 	case invoice.status
											    when "New" %> <span class="label label-inverse"><%= t('New') %></span>
											    <% when "Paid" %> <span class="label label-success"><%= t('Paid') %></span>
											    <% when "Unpaid" %> <span class="label label-warning"><%= t('Unpaid') %></span>
											    <% else %> <%= invoice.status %>
											    <% end %>
										    </td>
										    <td><%= invoice.created_at.strftime("%d/%m/%Y") %></td>
										    <td><%= invoice.expiredate.strftime("%d/%m/%Y") %></td>
										    <td><%= invoice.customer.fullname %></td>
										    <td><%= number_to_currency(invoice.amount) %></td>
										    
										    <td>
										    	
										    	
										    	<% if invoice.status == "Unpaid" || invoice.status == "New" %>
													
													<%= link_to t("Set paid"), invoice_path(invoice, :invoice => {:status => "Paid"}), :method => :put, :class => "btn btn-alt btn-mini btn-success", remote: true %>
													
												<% else %>
												
													<%= link_to t("Set unpaid"), invoice_path(invoice, :invoice => {:status => "Unpaid"}), :method => :put, :class => "btn btn-alt btn-mini btn-warning", remote: true %>

												<% end %>
												
												
												<% if invoice.invoicetype == "Quote" %>
													<%= link_to t("Became invoice"), invoice_path(invoice, :invoice => {:invoicetype => "Invoice"}), :method => :put, :remote => true, :class => "becameinvoice btn btn-alt btn-mini btn-inverse", :onclick => "$(this).parents('tr').appendTo('#invoices-table');" %>
												<% end %>
												
										    </td>

											<td class="toolbar">
												<div class="btn-group">											
													
													<%= link_to invoice do %>
												  		<button class="btn btn-small" data-toggle="tooltip" title="<%= t('view') %>" data-placement="bottom"><span class="icon-eye-open"></span></button>
													<% end %>
													
													<%= link_to edit_invoice_path(invoice, :invoicetype => invoice.invoicetype) do %>
														<button class="btn btn-small" data-toggle="tooltip" title="<%= t('edit') %>" data-placement="bottom"><span class="icon-pencil"></span></button>
													<% end %>
													
													<%= link_to invoice, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
														<button class="btn btn-small" data-toggle="tooltip" title="<%= t('delete') %>" data-placement="bottom"><span class="icon-remove"></span></button>
													<% end %>	
												</div>
											</td>

app/views/invoices/_invoicefield_fields.html.erb
<div class="controls">
<fieldset>
	<%= f.select :fieldtype, field_types, :class => "span2" %>
	<%= f.text_field :title, placeholder: t("Description"), :class => "span2" %>
	<%= f.text_field :units, placeholder: t("Units"), :class => "span1" %>
	<%= f.text_field :rate, placeholder: t("Rate"), :class => "span1" %>
	<%= f.text_field :amount, placeholder: t("Total"), :class => "span2" %>
	<%= f.hidden_field :_destroy %>
	<%= link_to t("[remove]"), "#", class: "remove_fields" %>
</fieldset>
</div>

app/views/invoices/destroy.js.erb
$("#tr_<%= @invoice.id %>").hide(1000, function () {
$(this).remove();
});

app/views/invoices/edit.html.erb
<div class="row">

	<article class="span12 dark data-block">
						<header>
							<h2><%= t('Editing invoice') %></h2>
							<ul class="data-header-actions">
								<li class="">
									<%= link_to t('Back'), invoices_path, :class => "btn btn-alt" %>
								</li>
							</ul>
						</header>
						<section class="tab-content">
							<!-- Tab #horizontal -->
							<div id="horizontal" class="tab-pane active">				
								<%= render 'form' %>
							</div>
							<!-- /Tab #horizontal -->
						</section>
	</article>
</div>

app/views/invoices/index.html.erb
		
				<!-- Grid row -->
				<div class="row">

					<!-- Data block -->
					<article class="span12 dark data-block">
						<header>
							<h2><%= t('Listing invoices') %></h2>
							<ul class="data-header-actions">
								<li>

									<%= link_to new_invoice_path(:invoicetype => "Invoice") do %>
								  		<span class="icon-file"></span> <%= t('Add invoice') %>
									<% end %>	

								</li>
							</ul>
						</header>
						
						<section>
							<table class="datatable table table-striped table-bordered table-hover" id="invoices-table">
								<thead>
									<tr>
										<th><%= t('Number') %></th>
									    <th><%= t('Status') %></th>
									    <th><%= t('Date') %></th>
									    <th><%= t('Expiredate') %></th>
									    <th><%= t('Customer') %></th>
									    <th><%= t('Amount') %></th>
									    <th><%= t('Actions') %></th>
									    <th></th>
									</tr>
								</thead>
								<tbody>
									
									<% @invoices.each do |invoice| %>
										<tr class="<%= cycle("gradeA even", "gradeA odd") -%>" id="tr_<%= invoice.id %>">
											<%= render partial: "invoice", object: invoice -%>
										</tr>
									<% end %>
								</tbody>
							</table>

						</section>

					</article>
					<!-- /Data block -->
					
				
					
					
					
					
					
					
					
					
					
					
					
					<!-- Data block -->
					<article class="span12 dark data-block">
						<header>
							<h2><%= t('Listing quotes') %></h2>
							<ul class="data-header-actions">
								<li>

									<%= link_to new_invoice_path(:invoicetype => "Quote") do %>
								  		<span class="icon-file"></span> <%= t('Add quote') %>
									<% end %>	

								</li>
							</ul>
						</header>
						
						<section>
							<table class="datatable table table-striped table-bordered table-hover" id="quotes-table">
								<thead>
									<tr>
										<th><%= t('Number') %></th>
									    <th><%= t('Status') %></th>
									    <th><%= t('Date') %></th>
									    <th><%= t('Expiredate') %></th>
									    <th><%= t('Customer') %></th>
									    <th><%= t('Amount') %></th>
									    <th><%= t('Actions') %></th>
									    <th></th>
									</tr>
								</thead>
								<tbody>
									
									<% @quotes.each do |quote| %>
  										<tr class="<%= cycle("gradeA even", "gradeA odd") -%>" id="tr_<%= quote.id %>">
											<%= render partial: "invoice", object: quote -%>
										</tr>
									<% end %>
								</tbody>
							</table>

						</section>

					</article>
					<!-- /Data block -->
					
					
					
				</div>
				<!-- /Grid row -->


		

		<!-- jQuery DataTable -->
		<%= javascript_include_tag "jquery.datatables.min" %>
		
		
		<script src="js/table_index.js"></script>
		
		
		

app/views/invoices/new.html.erb
<div class="row">
	<article class="span12 dark data-block">
						<header>					
							<h2><%= t('New invoice') %></h2>
							<ul class="data-header-actions">
								<li>
									<%= link_to t('Back'), invoices_path, :class => "btn btn-alt" %>
							</ul>
						</header>
						
						<section class="tab-content">
							<!-- Tab #horizontal -->
							<div id="horizontal" class="tab-pane active">	

								<%= render 'form' %>
								
							</div>
							<!-- /Tab #horizontal -->
						</section>							
	</article>
</div>

app/views/invoices/show.html.erb
<div class="row">
	<article class="span12 dark data-block">
		<header>
			<h2><%= t('Invoice') %> <%= @invoice.invoicenumber if @invoice.invoicenumber %></h2>
			<ul class="data-header-actions">
				<li class=""><%= link_to t('Back'), invoices_path %></li>
				<li class=""><%= link_to t('Edit'), edit_invoice_path(@invoice), :class => "btn btn-alt" %></li>
			</ul>
		</header>
		
		<section>
			<p>
			  <b><%= t('Type') %>:</b>
			  <%= @invoice.invoicetype %>
			</p>
			
			<p>
			  <b><%= t('Status') %>:</b>
			  <%= @invoice.status %>
			</p>
			
			<p>
			  <b><%= t('Expiredate') %>:</b>
			  <%= @invoice.expiredate %>
			</p>
			
			<p>
			  <b><%= t('Customer') %>:</b>
			  <%= @invoice.customer.fullname %>
			</p>
			
			<table class="table table-bordered table-striped">
									<thead>
										<tr>
											<th><%= t('Description') %></th>
											<th><%= t('Units') %></th>
											<th><%= t('Rate') %></th>
											<th><%= t('Price') %></th>
										</tr>
									</thead>
									<tbody>
										<% @invoice.invoicefields.each do |field| %>
										<tr>
											<td><%= field.title %></td>
											<td><%= field.units %></td>
											<td><%= field.rate %></td>
											<td><%= field.amount.to_s %><% if field.fieldtype.start_with?("percentage") %> % <% end %>  </td>
										</tr>
										<% end %>
										<tr>
											<td>
												<strong><%= t('Total') %></strong>
											</td>
											<td></td>
											<td></td>
											<td><strong><%= @invoice.amount %></strong></td>
										</tr>
										
									</tbody>
								</table>
			
		</section>
		
	</article>
</div>

app/views/invoices/show.js.erb
function blink(selector){
$(selector).fadeOut('slow', function(){
    $(this).fadeIn('slow', function(){
        blink(this);
    });
});
}
    
blink('.gradeA');

app/views/invoices/update.js.erb
$("#tr_<%= @invoice.id %>").fadeOut('fast');
$("#tr_<%= @invoice.id %>").fadeIn('fast');

$("#tr_<%= @invoice.id %>").html("<%= j render partial: "invoice", object: @invoice %>");