config/routes.rb
Invoicer::Application.routes.draw do
  resources :invoicefields

  resources :invoices

  resources :customers

  get "welcome/index"

  get "welcome/credits"

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
			


				<!-- Grid row -->
				<div class="row">
					
					<!-- Flexible block scaffolding example -->
					<div class="span12">

						<!-- Grid row -->
						<div class="row">

							<!-- Data block -->
							<%= link_to new_invoice_path(:invoicetype => "Invoice"), :class => "span2 data-block widget-block" do %>
								<section>
									<span class="icon-file-new-alt"></span>
									<strong><%= t('Add invoice') %></strong>
								</section>
							<% end %>
							<!-- /Data block -->
							
							<!-- Data block -->
							<%= link_to new_invoice_path(:invoicetype => "Quote"), :class => "span2 data-block widget-block" do %>
								<section>
									<span class="icon-file-new-alt"></span>
									<strong><%= t('Add quote') %></strong>
								</section>
							<% end %>
							<!-- /Data block -->

							<!-- Data block -->
							<%= link_to new_customer_path, :class => "span2 data-block widget-block" do %>
								  		<section>
									<span class="icon-address-book-alt"></span>
									<strong><%= t('Add customer') %></strong>
								</section>
							<% end %>	
							<!-- /Data block -->
							

						</div>
						<!-- /Grid row -->

					</div>
					<!-- /Flexible block scaffolding example -->


				</div>
				<!-- /Grid row -->


				<!-- Grid row -->
				<div class="row">
					


					<!-- Data block -->
					<article class="span12 turquoise data-block">
						<header>
							<h2><span class="icon-calendar"></span> <%= t("Calendar") %></h2>
						</header>
						<section class="tab-content">

							<!-- Tab #calendar -->
							<div class="tab-pane active" id="calendar">

								<div class='full-calendar full-calendar-demo'></div>

							</div>
							<!-- /Tab #calendar -->
							
							

						</section>
						<footer>
							<p><%= t('Invoices calendar') %></p>
						</footer>
					</article>
					<!-- /Data block -->
					
				</div>
				<!-- /Grid row -->



		<!-- jQuery FullCalendar -->
		<%= javascript_include_tag "jquery.fullcalendar.min" %>
		
		<script>
			$(document).ready(function(){
				
				// Tooltips
				$('[title]').tooltip({
					placement: 'top',
					container: 'body'
				});	

				// Tabs
				$('.demoTabs a, .demoTabs2 a').click(function (e) {
					e.preventDefault();
					$(this).tab('show');
					$('.fullcalendar').fullCalendar('render'); // Refresh jQuery FullCalendar for hidden tabs
				})

			});
		</script>
		
		<script>
			$(document).ready(function() {
			
				var date = new Date();
				var d = date.getDate();
				var m = date.getMonth();
				var y = date.getFullYear();
				$('.full-calendar-demo').fullCalendar({
					header: {
						left: '<%= t('today month,basicWeek') %>',
						center: 'title',
						right: 'prev,next'
					},
					buttonText: {
						prev: '<span class="icon-chevron-left"></span>',
						next: '<span class="icon-chevron-right"></span>'
					},
					editable: true,
					<% if I18n.locale == "it" %>
						buttonText: {
				            today: 'oggi',
				            day: 'giorno',
				            week:'settimana',
				            month:'mese'
				        },
						monthNames: ['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
						monthNamesShort: ['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Sett','Ott','Nov','Dic'],
						dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
						dayNamesShort: ['Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Dom'],
					<% end %>
					events: [
					
					<% Invoice.where(:invoicetype => 'Invoice').each do |invoice| %>
						
						
						{
							title: "<%= invoice.invoicenumber %> - <%= invoice.customer.fullname %>",
							date: "<%= invoice.expiredate.strftime("%Y-%m-%d") %>",
							allDay: true,
							className: "<%= invoice.status == "Unpaid" ? "event-orange" :  "event-turquoise" -%>",
							url: "<%= invoice_path(invoice) %>"
						},
					<% end %>
					]
				});
				
			});
		</script>		